### ISSUE TITLE
Please add requiemtls

### ISSUE THREAD

**Issue by 0xh3LL0** [LNReader/lnreader-plugins#1000]
### Source name

requiemtls

### Source link

requiemtls.com

### Language

english

### Other details

site similar to noblemtl and pandamtl which is already supported

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
adding requiemtls is harder than I thought, there needs to be a translator for it, I might make one in the future

**Comment by error7404** [comment]
i lied it was simple to do x)
