### ISSUE TITLE
Kolnovel new domain

### ISSUE THREAD

**Issue by ZakiLambo** [LNReader/lnreader-plugins#1001]
### Source information

Kolnovel

### Steps to reproduce

Kolnovel changed there domain

### Expected behavior

Changed domain

### Actual behavior

no results found

### LNReader version

2.0.0

### Android version

Android 8.1.0

### Other details

New domain
https://kolbook.xyz/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mingo3347** [comment]
When will this get fixed?

**Comment by nyagami** [comment]
Done in https://github.com/LNReader/lnreader-plugins/pull/1019

**Comment by Mingo3347** [comment]
Thanks for your work.Sent from my Galaxy
