### ISSUE TITLE
Search function on Novel Updates isn't working 

### ISSUE THREAD

**Issue by NawaSM** [LNReader/lnreader-plugins#1006]
### Source information

Novel Updates 

### Steps to reproduce

1. Open LNReader
2. Switch to the 'Browse' tab
3. Open the Novel Updates source
4. Try to search for any novel using the search bar 

### Expected behavior

it should load search results related to the query or indicate that there are no results.

### Actual behavior

It briefly loads and then displays the novels on the source's home screen as results, regardless of whatever you search for.
![Screenshot_20240628_115726_LNReader](https://github.com/LNReader/lnreader-plugins/assets/131329591/c9fade72-e05a-4556-8931-3cb8cf0cfd53)
![Screenshot_20240628_115740_LNReader](https://github.com/LNReader/lnreader-plugins/assets/131329591/e653cf41-f267-4800-a65d-0bdf14098982)
![Screenshot_20240628_115757_LNReader](https://github.com/LNReader/lnreader-plugins/assets/131329591/83cc727d-1330-467b-a575-c0910ce30ac5)

### LNReader version

2.0.0

### Android version

14

### Other details

I've tried installing other versions of LNReader but the issue persists. Other sources seem to be working fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
This is gonna get fixed soon.
#978

**Comment by NawaSM** [comment]
Noted
