### ISSUE TITLE
Mtlnovel.com 

### ISSUE THREAD

**Issue by Kayan877** [LNReader/lnreader-plugins#1010]
### Source name

Mtlnovel.com

### Source link
https://id.mtlnovel.com/index.php

### Language

Indonesian

### Other details

MTlnovel In English there is, while in Indonesian there isn't 

Sorry if my English is bad 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [x] I will fill out all of the requested information in this form.

**Comment by Kayan877** [comment]
> ## Peringatan: Tidak dapat memeriksa tema
> Masalah ini mungkin disebabkan oleh situs web ini**perlindungan awan suar**, URL tidak valid atau situs web sedang tidak aktif

re-check

**Comment by Kayan877** [comment]
> ## Warning: Could not check for themes
> This issue might be because this website has **cloudflare protection**, the URL is invalid or the website is down

https://id.mtlnovel.com/index.php

**Comment by Kayan877** [comment]
> ## Peringatan: Tidak dapat memeriksa tema
> Masalah ini mungkin disebabkan oleh situs web ini**perlindungan awan suar**, URL tidak valid atau situs web tidak aktif

Chinese theme

**Comment by Kayan877** [comment]
> ## Peringatan: Tidak dapat memeriksa tema
> Masalah ini mungkin terjadi karena situs web ini memiliki**perlindungan awan suar**, URL tidak valid atau situs web tidak aktif

Can you double check?

**Comment by error7404** [comment]
it's not an important warning

(the problem is that the site has cloudflare protection and the github action is getting stopped by the anti-bot protection (because he his a bot x) ))

**Comment by Kayan877** [comment]
is it not possible to add it

**Comment by error7404** [comment]
It is possible
