### ISSUE TITLE
Riwayat new domain

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#1011]
### Source information

فضاء الروايات (riwayat)

### Steps to reproduce

Riwayat changed their domain

### Expected behavior

Changed domain

### Actual behavior

No results found 

### LNReader version

2.0.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
what's the new domain?

**Comment by Mingo3347** [comment]
> what's the new domain?

riwyatspace.com

**Comment by Mingo3347** [comment]
The source is still not working, or will it work later?Sent from my Galaxy
-------- Original message --------From: nyagami ***@***.***> Date: 6/30/24  8:24 AM  (GMT+02:00) To: LNReader/lnreader-plugins ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [LNReader/lnreader-plugins] Riwayat new domain (Issue #1011) 
Closed #1011 as completed via #1012.

**Comment by nyagami** [comment]
you have to update riwayat to 1.0.4. If it still not working, try to clear cookies or open webview

**Comment by Mingo3347** [comment]
No update found it's saying, I also tried to clear cookies Sent from my Galaxy
-------- Original message --------From: nyagami ***@***.***> Date: 6/30/24  8:45 AM  (GMT+02:00) To: LNReader/lnreader-plugins ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [LNReader/lnreader-plugins] Riwayat new domain (Issue #1011) 
you have to update riwayat to 1.0.4. If it still not working, try to clear cookies or open webview

**Comment by error7404** [comment]
The plugins have changed to a newer version you need the new version of the app, you can download it here
https://github.com/LNReader/lnreader/actions/runs/9726810557

**Comment by Mingo3347** [comment]
I downloaded the newest version from the link but now the sources list is empty in every language and I don't understand what to do.Sent from my Galaxy
-------- Original message --------From: Justin COLLON ***@***.***> Date: 6/30/24  9:22 AM  (GMT+02:00) To: LNReader/lnreader-plugins ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [LNReader/lnreader-plugins] Riwayat new domain (Issue #1011) 
The plugins have changed to a newer version you need the new version of the app, you can download it here
https://github.com/LNReader/lnreader/actions/runs/9726810557

**Comment by Mingo3347** [comment]
Can I get an explanation on why does the sources dissappear when I download the new update from the link?

**Comment by error7404** [comment]
You need to install the plugin repo from here
https://lnreader.github.io/plugins
