### ISSUE TITLE
NovelUpdates not showing correct results

### ISSUE THREAD

**Issue by keenjramirez** [LNReader/lnreader-plugins#1025]
### Source information

NovelUpdates

### Steps to reproduce

1. Login to NU account via browser. 
2. Removed special characters from the title and tried several titles to make sure.
3. Cleared cache and data.
4. Uninstall and install again. 
![Screenshot_20240705_041056_LNReader](https://github.com/LNReader/lnreader/assets/154642618/ee69dea6-5914-4199-aa2b-fc9b8ff7c74b)
![Screenshot_20240705_041104_LNReader](https://github.com/LNReader/lnreader/assets/154642618/2c350051-83ea-4f47-9945-8290d4989226)

### Expected behavior

This should display the novel I am searching based on the browser search result. 

### Actual behavior

The same novel titles showed up instead and even if you try to search other titles the results are the same. 

### LNReader version

1.1.19

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
Novel Updates for 1.1.19 is broken and probably won't be fixed (not by me at least). App version 2.0.0 doesn't have this issue.

**Comment by keenjramirez** [comment]
> Novel Updates for 1.1.19 is broken and probably won't be fixed (not by me at least). App version 2.0.0 doesn't have this issue.

That's what i thought as well. I installed the version 2 but im still getting the same error.

**Comment by Batorian** [comment]
> > Novel Updates for 1.1.19 is broken and probably won't be fixed (not by me at least). App version 2.0.0 doesn't have this issue.
> 
> That's what i thought as well. I installed the version 2 but im still getting the same error.

Do you still have this issue? It's been long fixed by now.

**Comment by keenjramirez** [comment]
> > > Novel Updates for 1.1.19 is broken and probably won't be fixed (not by me at least). App version 2.0.0 doesn't have this issue.
> > 
> > 
> > That's what i thought as well. I installed the version 2 but im still getting the same error.
> 
> Do you still have this issue? It's been long fixed by now.

Yes i still have this issue

**Comment by Batorian** [comment]
Which version is your Novel Updates plugin?

**Comment by keenjramirez** [comment]
> Which version is your Novel Updates plugin?

Hello i just found out about the release of beta 2 and the issue is already resolved. Thank you for responding!
