### ISSUE TITLE
Need help in adding this repo to dantotsu

### ISSUE THREAD

**Issue by muneebusmani** [LNReader/lnreader-plugins#1028]
Hey there I love lnreader but I found dantotsu to do everything for me so I was wondering if lnreader extensions are like aniyomi and tachiyomi extensions, if yes, then how to add them to dantotsu?

**Comment by nyagami** [comment]
LNReader extentions (plugins) are written in TS/JS and not able to be executed by native Android app.

**Comment by muneebusmani** [comment]
Bruh then is there any way to connect kitu to lnreader?

**Comment by error7404** [comment]
currently, there is AniList and MAL as tracker, someone already requested it in https://github.com/LNReader/lnreader/issues/416

**Comment by muneebusmani** [comment]
> currently, there is AniList and MAL as tracker, someone already requested it in [LNReader/lnreader#416](https://github.com/LNReader/lnreader/issues/416)

bruh that issue is still open from 2022, bruh is it that hard to implement kitsu, bruh it has a better library than both mal and anilist, mal doesnt have many h-manga/manhwa in it, anilist doesn't has korean webnovels in it so thats why i use kitsu for tracking this stuff, because kitsu doesn't have these cons and has a bigger library than both, so sad to see that the feature request from 2022 is still not implemented

**Comment by error7404** [comment]
Bruh just implement it yourself, 
It's an open source project you know

**Comment by muneebusmani** [comment]
@error7404 i will try doing it so, the issue is that i know typescript but i never have done kotlin or any other languages which compiles directly to native android code

**Comment by error7404** [comment]
The project is in react native so the all project is in typescript

**Comment by muneebusmani** [comment]
@error7404 the thing is, the aniyomi app is built on kotlin , and it compiles to native android code, but lnreader is built on react native and i dont know if it compiles into android native code or not, i guess it doesn't, if it this wasn't the case , then the lnreader extensions should have been installed as an apk like aniyomi

**Comment by error7404** [comment]
Plugins are .js files but the LNReader app is react native that gets compiled to native code, and the tracker is written for the app side so in react native so in typescript
