### ISSUE TITLE
Kol novel

### ISSUE THREAD

**Issue by hamzaal7ref** [LNReader/lnreader-plugins#1031]
### Source name

Kol novel 

### Source link

https://kolbook.xyz/

### Language

Arabic 

### Other details

The new domain of kolnovel 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Duplicate of #1001

**Comment by hamzaal7ref** [comment]
How to do add the lnreader plugins please?

> Duplicate of #1001
