### ISSUE TITLE
Source Update: Genesis Translations -> Genesis Studio

### ISSUE THREAD

**Issue by TakaoRhaye** [LNReader/lnreader-plugins#1044]
### Source information

GenesisTls (possibly deprecated)

### Steps to reproduce

1. Go to GenesisTls source
2. Note that novels have not been updated for a while
3. Note the announcement about their URL change

### Expected behavior

Genesis Studios url should be used instead. 

https://genesistudio.com

### Actual behavior

The old Genesis Translations url is being used (which is going to go down within the next month).

### LNReader version

2.0.0

### Android version

Android 14

### Other details

Genesis Translations updated their URL to Genesis Studios (https://genesistudio.com). Note that this is a fully new site with a seemingly different front-end, so I'm not sure if any adjustments to the old source will be needed outside of updating the URL, but it likely will require some extra effort.

This issue may be better suited to a "Source Request" issue, but I'm putting it here for now as it's technically an issue with a previous source. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
Fixed in #1038.

**Comment by TakaoRhaye** [comment]
First time filling out a bug on this project, so I wasn't sure how a source update vs. request vs. bug was handled.

Also goes to show I should have checked open pull requests, thanks for the quick reply.

**Comment by TakaoRhaye** [comment]
(Reopening until https://github.com/LNReader/lnreader-plugins/pull/1038 is merged in order to track)

**Comment by Batorian** [comment]
I just saw I accidentally deleted my previous comment. My answer remains the same though. The PR mentioned above adds the new [Genesis Studio](https://genesistudio.com) as Plugin and replaces the old [Genesis Translations](https://genesistls.com).

**Comment by TakaoRhaye** [comment]
It's not merged to master yet, right? 

Did you want this issue closed before that branch was merged?
