### ISSUE TITLE
Chapter release date is wrong

### ISSUE THREAD

**Issue by DragonRaihan** [LNReader/lnreader-plugins#1048]
### Source information

Novelbuddy.io

### Steps to reproduce

Just open any Novelbuddy.io novel this happens
![Screenshot_20240713_135743_LNReader](https://github.com/user-attachments/assets/c4bfd0a0-24c3-489e-940f-d04d10a64065)

### Expected behavior

Chapter release date on App should match with original date or webview
![Screenshot_20240713_135935_LNReader](https://github.com/user-attachments/assets/d250eb1c-d4cc-4812-b6ec-49740fd2e0a4)

### Actual behavior

Chapter release date on App doesn't match the original release date
![Screenshot_20240713_140344_LNReader](https://github.com/user-attachments/assets/1d02cb11-a210-48fb-bbb4-54c577371cc9)
![Screenshot_20240713_140325_LNReader](https://github.com/user-attachments/assets/7759792f-e942-4082-aac9-80ce15af8caf)

### LNReader version

2.0.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
I took a look at it and honestly have no idea how the year+2 appears.

**Comment by DragonRaihan** [comment]
So is it fixed ?
