### ISSUE TITLE
Sorting dosent work sometimes

### ISSUE THREAD

**Issue by DragonRaihan** [LNReader/lnreader-plugins#1050]
### Source information

All source

### Steps to reproduce

https://github.com/user-attachments/assets/b05c56cb-fe2b-4185-912b-f6f0d4e0632e

### Expected behavior

Sorting should do as the way we selected.

### Actual behavior

Sorting goes haywire and it doesn't sort the way it suppose to 

https://github.com/user-attachments/assets/57cb83e2-e5e4-4196-8cc8-a0ac45a80b1c

### LNReader version

2.0.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
