### ISSUE TITLE
Novel fire: Filter by quantity

### ISSUE THREAD

**Issue by Gabriel062323** [LNReader/lnreader-plugins#1051]
### Source information

novelfire

### Steps to reproduce

use filter by quantity 

### Expected behavior

load novels

### Actual behavior

no load novels
![Screenshot_2024-07-13-04-46-36-288_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/a67c94e6-3d44-4e29-b6da-16c35c94d9b6)

![Screenshot_2024-07-13-04-46-44-528_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/6f478d38-e013-4aaa-b386-d28e66e4d909)

### LNReader version

2.0.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
Fixed in #1052.
