### ISSUE TITLE
All download option doesn't work

### ISSUE THREAD

**Issue by DragonRaihan** [LNReader/lnreader-plugins#1057]
### Source information

Ranobes

### Steps to reproduce

1. Open any novel from "Ranobes"
2. From download option click ALL Download
3. You need to use All Download for each page
![Screenshot_20240714_225442_LNReader](https://github.com/user-attachments/assets/3e2b07ed-d071-4e5a-9ba4-eec864db6edf)
![Screenshot_20240714_225436_LNReader](https://github.com/user-attachments/assets/c656202c-c3bb-4df1-872f-9464e0066b1d)

### Expected behavior

When we use option for All download as it stated it should download all chapters from the novel.

### Actual behavior

When ALL Download is used it just Download all chapters from currently opened chapter page.
To Download all chapters from the novel we need to use All Download for each chapter list page.
![Screenshot_20240714_225428_LNReader](https://github.com/user-attachments/assets/ec006fb5-d495-4a87-9573-bad35ddfebf8)
![Screenshot_20240714_225436_LNReader](https://github.com/user-attachments/assets/3073f0b9-f845-4925-be70-072888f9b90c)

### LNReader version

2.0.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
