### ISSUE TITLE
Issues loading and displaying chapter contents

### ISSUE THREAD

**Issue by 501stRookie** [LNReader/lnreader-plugins#1064]
### Source information

NovelUpdates

### Steps to reproduce

On some specific novels/links, when opening a chapter the chapter contents are not displayed.

Step 1: Open novel from library
Step 2: Open chapter from that source

### Expected behavior

The contents of the chapter load and display

### Actual behavior

It does not display the contents of the chapter, only a few of the links and text from the website

Example:
https://www.novelupdates.com/series/white-moonlight-omega-always-wants-to-possess-me/
https://app.yoru.world/en/story/181/read/3567

In app:
![image](https://github.com/user-attachments/assets/148e6d27-b9cd-46b9-b823-d491686d32d0)

Webview:
![image](https://github.com/user-attachments/assets/9ef989a6-6162-4110-8014-e9abe7e1053d)

### LNReader version

2.0.0-beta.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
This issue will be fixed in the next Novel Updates PR.
