### ISSUE TITLE
عودة طائفة جبل هوا

### ISSUE THREAD

**Issue by Yousef-art742** [LNReader/lnreader-plugins#1066]
### Describe your suggested feature

Fjy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing this issue because the translated text isn't descriptive. Feel free to reopen it after editing and adding more details.
