### ISSUE TITLE
The extension "Kolnovel" don't work

### ISSUE THREAD

**Issue by D4NTE-wq** [LNReader/lnreader-plugins#1068]
### Source information

Kolnovel

### Steps to reproduce

Opening Kolnovel 
It shows nothing 
The  domain of the actual site has been changed

### Expected behavior

It should show novels

### Actual behavior

It shows nothing

### LNReader version

1.1.20

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in commit 4bd7df1d61c84b26e3ce3b847b432b13430c0570
