### ISSUE TITLE
1.0.2 plugins filters

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader-plugins#1070]
### Source information

all

### Steps to reproduce

![Screenshot_2024-07-18-16-00-50-622_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/fb3d2c66-3de8-47ba-beb0-ac6a70ee7010)
This happens in all plugins 1.0.2 and up 

### Expected behavior

show filters 

### Actual behavior

filters in blank

### LNReader version

2.0.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
it's filters from multi-src not just version 1.0.2
