### ISSUE TITLE
Scribblehub unknown plugin 

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader-plugins#1072]
### Source information

Scribblehub 

### Steps to reproduce

1. Locate scribblehub 
2. Open source 

### Expected behavior

At this point, titles would show up

### Actual behavior

But instead it's just like this
![Screenshot_20240719-142652](https://github.com/user-attachments/assets/9004da82-f68d-47b2-9fb8-8c4f8b7bcbe8)

### LNReader version

2.0.0-beta 1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Try to uninstall the plugin and installing it back

**Comment by nyagami** [comment]
Changing plugin location from beta-1 to beta-2 caused this. Try to remove and add it again
