### ISSUE TITLE
Chapter is empty

### ISSUE THREAD

**Issue by RayzardDPC** [LNReader/lnreader-plugins#1080]
### Source information

Asura Light Novel

### Steps to reproduce

![Screenshot_20240722-131047_LNReader](https://github.com/user-attachments/assets/3a71de45-9f1c-42f1-97bc-090aee85a1eb)

### Expected behavior

The chapter should been showed by the last time i read

### Actual behavior

The chapter only show blank page

### LNReader version

1.1.19

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
seems like asura closed and is now a redirect to https://srankmanga.com/
