### ISSUE TITLE
blank chapters 

### ISSUE THREAD

**Issue by seiji-ror** [LNReader/lnreader-plugins#1092]
![Screenshot_2024-07-26-08-11-50-641_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/74b3e71d-ea7a-473c-882b-18e027800de9)

**Comment by error7404** [comment]
What plugin are you using, what novel is this, what version of the app are you using, and can you send a screenshot of it in WebView as well

**Comment by rajarsheechatterjee** [comment]
Closing this due to insufficient details. If the issue persists, please create a new issue and follow the issue template.
