### ISSUE TITLE
Linovelib can't be load properly

### ISSUE THREAD

**Issue by MareDevi** [LNReader/lnreader-plugins#1093]
### Source information

linovelib

### Steps to reproduce

open source
Choose any novel
![Screenshot_20240726_191407](https://github.com/user-attachments/assets/bcf97fb9-e375-41cf-9ec6-38b2d970f081)
![Screenshot_20240726_191403](https://github.com/user-attachments/assets/d912c262-8a21-4c9d-a00b-d6b0dc5f0e65)

### Expected behavior

Load properly

### Actual behavior

Cannot read property 'match' of
undefined

### LNReader version

1.1.19

### Android version

Android14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Try beta 2.0
(Don't forget to convert your backup)

**Comment by MareDevi** [comment]
> Try beta 2.0
> (Don't forget to convert your backup)

It works!!
Thank you very much and Thank you for such a wonderful app!
