### ISSUE TITLE
download cover option

### ISSUE THREAD

**Issue by Gabriel062323** [LNReader/lnreader-plugins#1095]
### Describe your suggested feature

make the covers downloadable in 2.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
That's a feature request for https://github.com/LNReader/lnreader
