### ISSUE TITLE
Moonlight Novels error when downloading

### ISSUE THREAD

**Issue by mazyuin** [LNReader/lnreader-plugins#1097]
### Source information

Moonlight Novels version 1.1.2 (also novelupdate version 0.7.3 when downloading from moonlight novels)

### Steps to reproduce

1. Download Moonlight Novels plugin
2. Open it and add any novel into library
3. Download unread chapters

### Expected behavior

The chapter should be downloaded

### Actual behavior

The chapter is not downloaded, the error i got is "DOWNLOAD_CHAPTER Expected URL scheme 'http' or 'https' but was 'data'

### LNReader version

2.0.0 (beta 2)

### Android version

Android 14

### Other details

There doesn't seem to be a problem with ratelimit, but the weird thing is, if there is a novel with 30 chapters, then there are some chapter that can be downloaded and some that can't be downloaded.
And on the other case with other novel that has 20-30 chapters, all the chapters can't be downloaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Can't reproduce, try to make a backup (Google drive recommended) and unintalle the app

**Comment by mazyuin** [comment]
I uninstalled the app, then reinstall from : 
[https://github.com/LNReader/lnreader/releases/download/v2.0.0-beta.2/lnreader-v2.0.0-beta.2.apk](url)
But i still got the same error Expected URL scheme 'http' or 'https' but was 'data'
The novel i'm trying to download from Moonlight Novels is Ghost Story Club.

**Comment by mazyuin** [comment]
Oh now it is fixed by downloading the latest action build : 
[https://github.com/LNReader/lnreader/actions/runs/10003215907](url)
The problem only occuring on the apk from [https://github.com/LNReader/lnreader/releases/download/v2.0.0-beta.2/lnreader-v2.0.0-beta.2.apk](url)

**Comment by mazyuin** [comment]
Fixed by downloading the latest action build.
