### ISSUE TITLE
Mtlnovel date filter not working 

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader-plugins#1107]
### Source information

Mtlnovel

### Steps to reproduce

Open plugin, select  date, click search

### Expected behavior

.. 

### Actual behavior

![Screenshot_2024-08-03-18-24-49-534_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/15c32403-950c-4e27-8e61-dd1dd02b53e7)
![Screenshot_2024-08-03-18-24-54-931_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/a557de03-e663-4b7e-af09-3473cc9dd4b5)

### LNReader version

2.0.0

### Android version

13

### Other details

Can you add search by genres to the filters? Please 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
The probleme comes from the site of you try sort novels by date it doesn't work, it might get fixed by them sometime ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by WGmg23** [comment]
> The problem comes from the site if you try to sort novels by date it doesn't work, it might get fixed by them sometime ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
> 
> https://www.mtlnovel.com/novel-list/?orderby=date (don't work) https://www.mtlnovel.com/novel-list/?orderby=rating (works)

Thank you
