### ISSUE TITLE
Edit site plugins

### ISSUE THREAD

**Issue by Qiskdbwob** [LNReader/lnreader-plugins#1115]
### Describe your suggested feature

Features for editing the plugins site itself, for example, daonovels plugins that have moved sites or changed site addresses by adding a setting feature to the plugins.

### Other details

Plugins with additional settings in each plugins so that each plugin has a setting button to edit it such as editing the plugin icon, name, plugin address, and others.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
that's an issue for https://github.com/LNReader/lnreader
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).

**Comment by rajarsheechatterjee** [comment]
I'm not sure of a use case for your suggestion. However, you're always welcome to fork the repository, make the changes, and add your fork as a repository in the app. If it's just a URL change, you could raise a PR for the main repository to fix it for everyone.

**Comment by error7404** [comment]
daonovels is a special one there is a new site but there is some novels that are still on the old site, so I'm not touching it until they have just 1 simple website
