### ISSUE TITLE
Free Web Novel(en): change plugin name to FreeWebNovel

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader-plugins#1117]
### Describe your suggested feature

As the title says.

### Why
If you google "Free Web Novel" no trace of the website will appear.
If you google "freewebnovel" it will appear.
Given the fact the words in the nane are way too generic, making the name whole would be better to identify it

### Other details

![Screenshot_20240806-173026_1](https://github.com/user-attachments/assets/b6a86873-b0df-4160-b9cd-7733db2024a4)
![Screenshot_20240806-173048_1](https://github.com/user-attachments/assets/e7c95fa2-2837-4357-93c9-1503b5012a9f)
Even searching a bit, i dont see places where they write the name with spaces.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The name on their site in Free Web Novel seems to be correct, so I don't think the app should change it.

**Comment by Palloxin** [comment]
Even stable named the extension FreeWebNovel
![Screenshot_20240811-091047_1](https://github.com/user-attachments/assets/b9281543-9344-4542-932d-1fe74a616436)

A name is used when searching it. If it doesnt appear on google what's the point.

**Comment by nyagami** [comment]
It is their SEO problem, not app's.

**Comment by Palloxin** [comment]
It's just incovenient. When typing "freeweb" to search the plugin nothing apprears. It's more intuitive the whole version

**Comment by rajarsheechatterjee** [comment]
> They don't even use it in the website itself, that's why it doesnt appear on google, but only with the whole form.

Why would a piracy site want to appear on Google? They do use 'Free Web Novel' if you check the tab title or inspect the site's HTML.
