### ISSUE TITLE
Chapter is empty

### ISSUE THREAD

**Issue by Blackhead9918** [LNReader/lnreader-plugins#1119]
### Source information

Baca Light Novel

### Steps to reproduce

![Floatee_1722983996009](https://github.com/user-attachments/assets/a8e7a377-3d71-497c-a1d5-668833bc1986)

1.Search for novels on bacalightnovel 
2. Start reading 
3.chapter is empty

### Expected behavior

I tried In the web view there is 

### Actual behavior

Chapter is empty

### LNReader version

Beta 2.0.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
That what I forgot to fix, oops

**Comment by Blackhead9918** [comment]
Can you also change the url morenovel.com to risenovel.com 😅🙏
