### ISSUE TITLE
Vietnamese source change domain 

### ISSUE THREAD

**Issue by Karutovn** [LNReader/lnreader-plugins#1148]
New domain for hako: https://docln.net
New domain for light novel vn: https://lightnovel.vn/
New domain for truyenfull: https://truyenfull.io/

**Comment by nyagami** [comment]
I think docln.net is the old domain of Hako

**Comment by Karutovn** [comment]
> I think docln.net is the old domain of Hako

But if i go to webview, it's direct to this domain :D

**Comment by nyagami** [comment]
There might be some hardcoded chapter/novel url

**Comment by rajarsheechatterjee** [comment]
@Karutovn Please follow the issue template going forward. Without those details, it’s hard to triage issues.
