### ISSUE TITLE
Rainofsnow isn't displaying novel information after clicking on a novel

### ISSUE THREAD

**Issue by glitch-m0de** [LNReader/lnreader-plugins#1154]
### Source information

Rainofsnow

### Steps to reproduce

1. Browse rainofsnow
2. Click any novel
3. Displays a blank screen

### Expected behavior

Novel information should be shown after clicking on a novel.

### Actual behavior

Displays a blank screen instead.

https://github.com/user-attachments/assets/fe320112-3add-4227-a72b-74286b5e0a6c

### LNReader version

2.0.0-beta2

### Android version

Android 14

### Other details

I have tried using both Wi-Fi and mobile data, waiting it out (tested for 30 mins.), and even uninstalling the app, nothing. It should be noteworthy to say that it does work fine on version 1.1.19.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by glitch-m0de** [comment]
Hi, I don't think the issue has been resolved 😔 Or is there anything I should do to make it work? 

https://github.com/user-attachments/assets/2d658b0c-8607-46eb-943a-b2053fd3bc22

**Comment by K1ngfish3r** [comment]
Find one bug, squash it. 99 more bugs in the code. Gonna figure this out somehow
