### ISSUE TITLE
Scribble Hub search nonfunctional

### ISSUE THREAD

**Issue by CheshireCat27** [LNReader/lnreader-plugins#1168]
### Source information

Scribble Hub

### Steps to reproduce

2.0.0 r1017, install Scribble Hub plugin, open search bar and search something.

### Expected behavior

Returns search results.

### Actual behavior

Reloads page, but doesn't return any results and shows the same stories.

### LNReader version

2.0.0 r1017

### Android version

Android 14

### Other details

S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Can't reproduce, What's the plugin version & what is your repo's version?

**Comment by CheshireCat27** [comment]
Plugin version 1.0.1
Unsure how to verify repo version, just grabbed the link from the website.

I believe I have narrowed it down, plugin does not seem to support filtering stories via artist name.

**Comment by CheshireCat27** [comment]
;-;

Thanks for the quick response.
