### ISSUE TITLE
[Source Request] Namevt

### ISSUE THREAD

**Issue by Clousry** [LNReader/lnreader-plugins#1177]
### Source name

Namevt

### Source link

https://namevt.com/

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Lighnovelwp Theme (but the GH action is still not fixed #1158)
