### ISSUE TITLE
MTL Novel source not updating any novels

### ISSUE THREAD

**Issue by Hymntnc** [LNReader/lnreader-plugins#1198]
### Source information

MTL Novel English 1.1.1

### Steps to reproduce

Open any novel in the library that is connected to MTL Novel and do one of the following:
* Pull down chapter list until refresh icon displays - will receive can't parse page message.
* click on WebView - will see page requesting password.

Images below
![20240924_221410](https://github.com/user-attachments/assets/d1b40a08-f91c-405b-a0ec-98f1dd0284ef)
![20240924_221347](https://github.com/user-attachments/assets/ffbfaf1c-d484-42ad-97fc-f8be2d94fb72)
![20240924_221247](https://github.com/user-attachments/assets/100b1889-971f-448b-9ce3-96d6fbd7ac1c)

### Expected behavior

Chapters should update

### Actual behavior

Get error or request for password 

### LNReader version

2.0.0-beta.2

### Android version

13

### Other details

This is happening on more than on device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
They seam to have changed url but only for the English version of the site
