### ISSUE TITLE
Riwayat domain change

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#1223]
### Source information

Riwayat 

### Steps to reproduce

Domain changed 

### Expected behavior

Updated domain

### Actual behavior

Error

### LNReader version

2.0.0

### Android version

Android 11

### Other details

cenele.com
https://cenele.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Abdalrhman1235** [comment]
.dist/plugins.json

**Comment by Mingo3347** [comment]
?
