### ISSUE TITLE
Kolnovel domain change

### ISSUE THREAD

**Issue by Geesama02** [LNReader/lnreader-plugins#1226]
### Source information

Kol novel

### Steps to reproduce

Kol novel domain got changed

### Expected behavior

The source doesnt work

### Actual behavior

The domain must be changed to the new one

### LNReader version

1.1.19

### Android version

One ui 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Abdalrhman1235** [comment]
.dist/plugins.json
