### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AzaleaW** [LNReader/lnreader-plugins#1241]
My only sources are Anilist and MyAnimeList!
![Screenshot_20241025_094505_LNReader](https://github.com/user-attachments/assets/fc3e9c05-bafd-40c0-9fb1-1baa8c1fed00)

**Comment by error7404** [comment]
LNReader no longer includes pre-installed plugin repositories.

Add Repository
https://lnreader.github.io/plugins

**Comment by AzaleaW** [comment]
> LNReader no longer includes pre-installed plugin repositories.
> 
> Add Repository https://lnreader.github.io/plugins

I did but nothing new shows

**Comment by error7404** [comment]
Go to the available tab, and refresh the tab
