### ISSUE TITLE
LN reader

### ISSUE THREAD

**Issue by Kleinmoretti247** [LNReader/lnreader-plugins#1251]
### Source name

Klein

### Source link

I don't know

### Language

Indonesia

### Other details

When I want to download or update a chapter in LNreader, it always gives an error and always exits the application. also there is always the info "LNreader has stopped". I don't know what that means, there's no problem with the plugins. can any of you help

note: I don't know what to write about
*source name* 
*source title and source link*

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Please avoid creating duplicate issues, and make sure to submit them in the correct repository.
