### ISSUE TITLE
Pls add three sources 

### ISSUE THREAD

**Issue by Aruraka** [LNReader/lnreader-plugins#1252]
### Source name

My drama novel.com, wuxia click nd wuxia box

### Source link

https://mydramanovel.com/,https://wuxia.click/,https://www.wuxiabox.com/

### Language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Please open individual issues per sources, and don't create duplicate issues
