### ISSUE TITLE
Novel site

### ISSUE THREAD

**Issue by turkceokuyucu** [LNReader/lnreader-plugins#1269]
### Source name

Noveltr

### Source link

https://noveltr.com/

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
this source was added already

**Comment by nyagami** [comment]
What? Have you even opened the app? It already existed in app

**Comment by EMRULLAHPALAZ** [comment]
No, there are only a few sites and most of the sites I sent were rejected,
I wonder why. (The translation is a bit bad, I'm sorry if I made the series
angry.)
5 Kas 2024 Sal 18:33 tarihinde nyagami ***@***.***> şunu
yazdı:

**Comment by nyagami** [comment]
Because your requests were added before

For example, here is Noveltr in app
![Screenshot_20241105-224733](https://github.com/user-attachments/assets/626f44a2-d067-4432-af6d-b34ef63a277a)

**Comment by EMRULLAHPALAZ** [comment]
Dude, seriously, no, why would I lie? That site hasn't been added and many
sites I've sent to have been rejected. Why were these rejected?
For example, why were https://araznovel.com/ and https://namevt.com/
rejected?
There is no explanation for these, you just wrote that they were sent
before and you wrote something like automatic action. Not even one of my
requests was accepted.

5 Kas 2024 Sal 18:49 tarihinde nyagami ***@***.***> şunu
yazdı:

**Comment by Woundez** [comment]
because its already added

**Comment by EMRULLAHPALAZ** [comment]
Dude, why aren't there any sites in the screenshots I posted? There are
only 4 sites and 3 of them are active.

5 Kas 2024 Sal 18:57 tarihinde Woundez ***@***.***> şunu
yazdı:

**Comment by Woundez** [comment]
where did u post the screenshots?

**Comment by nyagami** [comment]
What is your app version

**Comment by Woundez** [comment]
are u in the discord server if not then join

**Comment by rajarsheechatterjee** [comment]
> For example, why were https://araznovel.com/ and https://namevt.com/
rejected?
There is no explanation for these, you just wrote that they were sent
before and you wrote something like automatic action. Not even one of my
requests was accepted.

@EMRULLAHPALAZ  There are comments on those issues pointing out that duplicate issues were created, along with links to the original issues. The issue form clearly mentions checking for existing requests before submitting. Repeatedly creating duplicates clutters the system, so please review open issues before posting.

**Comment by EMRULLAHPALAZ** [comment]
There are only these 3 sites and there are no sites you rejected, if you
want, check from the application

5 Kas 2024 Sal 19:00 tarihinde EMRULLAH PALAZ ***@***.***>
şunu yazdı:

**Comment by EMRULLAHPALAZ** [comment]
I'm on the server what's your name

5 Kas 2024 Sal 19:02 tarihinde Woundez ***@***.***> şunu
yazdı:

**Comment by Woundez** [comment]
@wound

**Comment by Woundez** [comment]
just post screenshots in the support channel

**Comment by EMRULLAHPALAZ** [comment]
@alucard_dracula31 bu benim etiketim

5 Kas 2024 Sal 19:04 tarihinde Woundez ***@***.***> şunu
yazdı:

**Comment by EMRULLAHPALAZ** [comment]
@alucard_dracula31 This is my tag

5 Kas 2024 Sal 19:06 tarihinde EMRULLAH PALAZ ***@***.***>
şunu yazdı:
