### ISSUE TITLE
Only showing last 25 chapters: Ranobes

### ISSUE THREAD

**Issue by minjaesong04** [LNReader/lnreader-plugins#1299]
### Source information

Ranobes

### Steps to reproduce

1. Download the Ranobes extension
2. Open any LN with more than 25 chapters
3. It will display the last 25 chapters only

### Expected behavior

It should show all the chapters leading up to the last 25 and the last 25.

### Actual behavior

However, only the last 25 chapters are being shown

### LNReader version

2.0.0

### Android version

14

### Other details

I think this issue is being caused as the Ranobes website displays only the last 25 chapters in the initial chapter list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Have you tried pressing the "page: 1" button?

**Comment by minjaesong04** [comment]
oml you are absolutely right, i never figured that it was a button
