### ISSUE TITLE
novels don't parse in novel updates

### ISSUE THREAD

**Issue by mohamedku53** [LNReader/lnreader-plugins#1304]
### Source information

novel updates

### Steps to reproduce

open any novel

### Expected behavior

it parses

### Actual behavior

cant parse

### LNReader version

LNReader v2.0.0-beta.2

### Android version

8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Are you logged into WebView?

**Comment by mohamedku53** [comment]
![Screenshot_٢٠٢٤١١٠٧-٢١٣٧٤٨](https://github.com/user-attachments/assets/4b1fca04-f090-4813-bf67-1e40be15b334)
