### ISSUE TITLE
I became an immortal in the mortal workd

### ISSUE THREAD

**Issue by Clarence21-hub** [LNReader/lnreader-plugins#1308]
### Source name

Noveltop1

### Source link

Hsha

### Language

ENGLISH 

### Other details

Need chapter 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
duplicate of #314 
Please provide a source link next time
