### ISSUE TITLE
Could not reach site (500) try to open in webview

### ISSUE THREAD

**Issue by glitch-m0de** [LNReader/lnreader-plugins#1311]
### Source information

Citrus Aurora

### Steps to reproduce

1. Click the source
2. Shows error

### Expected behavior

It should show the novels. 

### Actual behavior

This is what is shown instead. :(

![Screenshot_2024-11-10-12-16-40-68_3c1c179116822eec69c21805387f0489](https://github.com/user-attachments/assets/db02b59c-29c7-4a2b-8215-b7eeaf11bf37)

https://github.com/user-attachments/assets/940f6f7c-6c5f-443c-a728-6d6aa3373384

### LNReader version

2.0.0-beta2

### Android version

Android 14

### Other details

I don't think Citrus Aurora updated their website like Dusk Blossoms, so I'm confused why it's suddenly getting an error like this :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
I can't reproduce it can you try to clear your WebView data or using a DNS/vpn?

**Comment by glitch-m0de** [comment]
that qorker
