### ISSUE TITLE
Doulou Dalu 3: Legend of the dragon 

### ISSUE THREAD

**Issue by Kautsar-10** [LNReader/lnreader-plugins#1315]
Can't read because no text appears

**Comment by Kautsar-10** [comment]
please give steps or text so that i can read the novel doulou dalu 3

**Comment by Kautsar-10** [comment]
please give steps or text so that i can read the novel doulou dalu 3

**Comment by rajarsheechatterjee** [comment]
Please follow the issue template and fill in the required information. Otherwise, it’s difficult to debug issues.
