### ISSUE TITLE
ranobelib stopped working

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader-plugins#1322]
### Source information

ranobehub

### Steps to reproduce

The source just stopped working completely
The ranobelib site itself is working (web)
[](url)
![clipboard0-horz](https://github.com/user-attachments/assets/993ca5fe-ea28-4ec8-b44f-a1e94c05e53f)

### Expected behavior

For the source to work

### Actual behavior

The source is not working.

### LNReader version

2.0.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rider21** [comment]
Do you have access to this site?
https://api.lib.social/api/manga/
