### ISSUE TITLE
ranobelib does not see some chapters

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader-plugins#1340]
### Source information

ranobelib

### Steps to reproduce

ranobelib does not see some chapters
For example, let's take this - https://ranobelib.me/ru/book/78570--goshujin-sama-to-yuku-isekai-survival-web-novel?bid=15700&section=chapters

When we select the translator "Затексурье" in the program, we do not see all the chapters, but if we go through the Web and select the same translator, there are more chapters. In general, everything is visible in the screenshot.

![cats](https://github.com/user-attachments/assets/d44a5fad-f67a-4549-b2f9-e6c68f80f6e5)

### Expected behavior

So that all chapters are visible

### Actual behavior

Some chapters are simply lost, although they should be there.

### LNReader version

Github Action 2.0.0 (26/11/24 04:41 PM UTC) Commit: 5db79a09

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Farori** [comment]
same problem https://github.com/LNReader/lnreader-plugins/issues/1143

**Comment by VectorNEON** [comment]
After updating the plugin to 2.1.1, the novel does not open (https://ranobelib.me/ru/book/78570--goshujin-sama-to-yuku-isekai-survival-web-novel)
![image](https://github.com/user-attachments/assets/992fda09-cc3b-4774-8fc2-1566d6b52e5f)
Other novels are opening, of course I haven’t checked everything, but there is a problem with this one, I waited a long time, but there was no result.
