### ISSUE TITLE
Turkish source

### ISSUE THREAD

**Issue by EMRULLAHPALAZ** [LNReader/lnreader-plugins#1364]
### Source name

Fenrircans

### Source link

fenrirscans.com

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by EMRULLAHPALAZ** [comment]
I have sent a question before asking why this site is not added and I have not received an answer as to why it is not added. I also did the same for a few other sites and still didn't get a response. 
https://fenrirscans.com/
https://novelokur.com.tr/
https://turkcenoveloku.blogspot.com/
https://novelaozora.com/
https://www.felisnovel.com/
https://lnmakineceviri.blogspot.com/?m=1
https://hipertales.com/
Why are these sites not added?

**Comment by CD-Z** [comment]
All the people working on this project do it in their free time and don't get paid to do it. So there is no reason or responsibility to add new plugins except ones own desire. And as far as I know there are no Turkish contributors, that means there is no one who wants to add these sites. 
You can only wait until there is someone who wants to add these or learn to do it yourself. If you want to learn you can join the discord where you can find help if you get stuck.

**Comment by nyagami** [comment]
![Screenshot_20241210-181623.png](https://github.com/user-attachments/assets/bae0eb20-f64d-4640-b9d5-14d8a7169e9e)

Have you ever opened the app?

**Comment by EMRULLAHPALAZ** [comment]
Can I ask you to add these? Also, I couldn't fully understand my problem because of the translation. I don't have any intention of getting angry with you, I just wanted to ask, thank you. Also, there was a problem in the Turkish section, I will write it here and you can fix it.
![Screenshot_2024-12-10-16-12-57-088_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/abf1b86f-bb17-4cbb-982f-ed3d58a95e16)
This site is not working and I should have written before, this site is not a Turkish site, could you please fix this?

**Comment by nyagami** [comment]
You should check if your requests were created before.
![image](https://github.com/user-attachments/assets/b73a6015-3e48-471a-bb0e-a3420260b032)

I dont understand Turkish so I cant fix it, Wait for someone understand Turkish
