### ISSUE TITLE
Endless loading MTL Hovel (RU)

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader-plugins#1385]
### Source information

MTL Hovel (RU)

### Steps to reproduce

When you select any novel in MTL Hovel (RU), an endless loading occurs
![image](https://github.com/user-attachments/assets/4600f1bd-bf03-4dcd-a337-87f1fcc07d6a)
![image](https://github.com/user-attachments/assets/893f2ce8-8dcc-4f31-af16-43eec5c1fe2a)

### Expected behavior

Should work

### Actual behavior

doesn't work

### LNReader version

2.0.0 beta3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Have you tried to access a novel thought WebView, or tried a VPN, because it works fine for me

**Comment by VectorNEON** [comment]
> Have you tried to access a novel thought WebView, or tried a VPN, because it works fine for me

Apparently my provider was buggy, but everything really works.
