### ISSUE TITLE
Request to add Nanomashin as a new source

### ISSUE THREAD

**Issue by zexinXzexin** [LNReader/lnreader-plugins#201]
### Source name

Nanomashin

### Source link

https://www.nanomashin.online/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Humam-Hamdan** [comment]
There's a new link
https://skydemonorder.com/

**Comment by nyagami** [comment]
duplicated of [#231](https://github.com/LNReader/lnreader-plugins/issues/231)
