### ISSUE TITLE
LightNovelReader: Search Broken

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-plugins#219]
### Source information

lightnovelreader.org

### Steps to reproduce

Search novel in lightnovelreader.org

### Expected behavior

novel search from lightnovelreader.org should appear 

### Actual behavior

I tried searching novels in lightnovelreader.org and all search results received are resulting like this. No matter what name I input, all search results are the same ..

![Screenshot_2022-05-04-10-32-14-30](https://user-images.githubusercontent.com/25120376/166617845-be79b5ec-579c-4c73-a6c9-59ecc65f41be.jpg)

![Screenshot_2022-05-04-10-31-47-84](https://user-images.githubusercontent.com/25120376/166618073-347ab062-0034-4628-a4b4-65767eefbcc7.jpg)

### LNReader version

v1.1.10

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.8](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The the app is using the detailed search present on the website which seems to return the same search result.

**Comment by nyagami** [comment]
It was moved to ReadLiteNovel in v2 app
You should use v2 beta app or wait for its stable release
