### ISSUE TITLE
ElloMTL

### ISSUE THREAD

**Issue by Humam-Hamdan** [LNReader/lnreader-plugins#262]
### Source name

ElloMTL

### Source link

https://ellomtl.xyz

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
I think it's been changed to ElloMTL and done in https://github.com/LNReader/lnreader-plugins/pull/867
