### ISSUE TITLE
Add Brazilian source Novel Mania

### ISSUE THREAD

**Issue by Unkyyy** [LNReader/lnreader-plugins#334]
### Source name

Novel Mania

### Source link

https://novelmania.com.br/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by kudse** [comment]
Hi,

There is any update on this request, i almost open a new issue to ask this source again, if anyone could take this i appreciate.

https://novelmania.com.br/

**Comment by felipebonfim2006** [comment]
> Hi,
> 
> There is any update on this request, i almost open a new issue to ask this source again, if anyone could take this i appreciate.
> 
> https://novelmania.com.br/

added
