### ISSUE TITLE
[Source Request] MTLSQUAD 

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-plugins#372]
### Source name

MTLSQUAD

### Source link

https://mtlsquad.com/novel/

### Language

English

### Other details

Good alternative for mtlnation. Most faloo novel (MTL) I only found in ReadWn and mtlnation, some of them can be found in this source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Site seems to be down
