### ISSUE TITLE
WuxiaWorld: generally broken

### ISSUE THREAD

**Issue by semiya5** [LNReader/lnreader-plugins#401]
### Source information

WuxiaWorld

### Steps to reproduce

Open extension
Select a series

### Expected behavior

Should grab all info

### Actual behavior

Get no cover, chapter list, or series status

### LNReader version

1.1.13

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
You should use v2 beta app or wait for its stable release
