### ISSUE TITLE
Booktoki 

### ISSUE THREAD

**Issue by Acentin** [LNReader/lnreader-plugins#426]
### Source name

BookToki

### Source link

https://booktoki164.com/

### Language

Korean

### Other details

A good Korean website to read novels. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
duplicated of https://github.com/LNReader/lnreader-plugins/issues/606
