### ISSUE TITLE
Arabic source

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#461]
### Source name

Olaoe.cyou

### Source link

https://www.google.com/url?sa=t&source=web&rct=j&url=https://olaoe.cyou/works/%25D8%25B1%25D9%2588%25D8%25A7%25D9%258A%25D8%25A9-%25D9%2581%25D8%25B5%25D9%2584-%25D8%25A7%25D9%2584%25D9%2586%25D8%25AE%25D8%25A8%25D8%25A9-%25D9%2585%25D8%25AA%25D8%25B1%25D8%25AC%25D9%2585%25D8%25A9-%25D9%2585%25D9%2586-%25D8%25A8%25D8%25B9%25D8%25AF-%25D8%25A7%25D9%2584%25D8%25A7%25D9%2586%25D9%2585%25D9%258A/&ved=2ahUKEwiIw6_N_6n9AhXC9rsIHQ67C1sQFnoECCcQAQ&usg=AOvVaw1bm0VIk-6NGF5wIPUGdZiA

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
that's a manga website
