### ISSUE TITLE
LightNovelReader not updating

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [LNReader/lnreader-plugins#503]
### Source information

LightNovelReader

### Steps to reproduce

1. Try updating a novel from the source LightNovelReader or a Global Update
2. Open up webview and check if new chpaters have been added.

### Expected behavior

The new chapters should appear in the app

### Actual behavior

The new chapters don't appear in app. This can be confirmed by opening webview and checking.

### LNReader version

1.1.15

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
It was moved to ReadLiteNovel in v2 app
You should use v2 beta app or wait for its stable release
