### ISSUE TITLE
Source request Novelbin

### ISSUE THREAD

**Issue by SpitfireUst** [LNReader/lnreader-plugins#515]
### Source name

novelbin

### Source link

https://novel-bin.net/

### Language

English

### Other details

Has a lot of (non mtl) novels and novels missing from current sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Sometime back, https://novelbin.com/ was added to the app. Are there any differences between it and the URL you have requested?
