### ISSUE TITLE
Sources issues

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader-plugins#566]
There an issue saying cannot read property trim...please resolve this issue.

**Comment by rajarsheechatterjee** [comment]
This doesn't have any info to debug the issue. Please follow the [issue template](https://github.com/LNReader/lnreader-sources/issues/new?assignees=&labels=Bug&projects=&template=report_issue.yml).

**Comment by TonyRaj02** [comment]
![Screenshot_2023-08-15-20-57-45-16_3c1c179116822eec69c21805387f0489.jpg](https://github.com/LNReader/lnreader-sources/assets/142190516/24c8b77b-7fa2-4006-8c94-fa091ae54202)

See even after going through the process that is shown in picture but it's still failed in update..please solve this
