### ISSUE TITLE
Working new sources

### ISSUE THREAD

**Issue by iaacautomation** [LNReader/lnreader-plugins#576]
### Describe your suggested feature

https://www.lightnovelcave.com/
https://lightnovels.live/

### Other details

Found a few new sources seem to be working while some others are broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by deku99hh** [comment]
I just downloaded lnreader.  I was trying to find the novel "my vampire system" in the Arabic sources, but it is not there.
So can you put this source https://rewayat.club/
