### ISSUE TITLE
LightNovelWorld

### ISSUE THREAD

**Issue by JeffBezosSniffer** [LNReader/lnreader-plugins#613]
### Source name

Lightnovelworld

### Source link

https://www.lightnovelworld.com

### Language

English

### Other details

I have been using this site for a while and i can say its good and reliable i would appreciate it being in lnreader so I can download novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
Lightnovelpub bro
