### ISSUE TITLE
LightNovelPub release date bug

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader-plugins#632]
### Source information

LightNovelPub (en)

### Steps to reproduce

1. LightNovelPub, add Infinite Mana in the apocalipse to the library
2. download the last 100 chapters
3. Turn off internet from the device for a day minimum (absolutely no internet)
4. Turn on internet and update that entry

### Expected behavior

The release date of chapters has a properly working time counter

### Actual behavior

Time counter doesnt time count properly
![IMG_20231025_203025](https://github.com/LNReader/lnreader/assets/75091899/c527321c-7430-4472-8ff4-de5c996acab6)

Multiple release dates 

https://github.com/LNReader/lnreader/assets/75091899/c14d2df1-861d-47bd-b779-54b1e9f5d6b9

### LNReader version

1.1.18

### Android version

Android 8

### Other details

The reproduction steps are just what i did. I cant garantee it will be reproduced.
I thought it was a problem of the  app but Traitor said to report it here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
You should use v2 beta app or wait for its stable release
