### ISSUE TITLE
LightNovelPub: Chapter numbers missing

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader-plugins#640]
### Source information

LightNovelPub

### Steps to reproduce

nothing, just visit a random entry of the source

### Expected behavior

The source retrieves chapter number

### Actual behavior

The source only retrieves source titles

### LNReader version

1.1.18

### Android version

A8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Are the Chapter Numbers present on the source website?

**Comment by Palloxin** [comment]
my bad i misclicked, anyway... yes
![IMG_20231109_205147](https://github.com/LNReader/lnreader-sources/assets/75091899/31be2e7c-3ce2-435b-82b3-868f030b2aa3)

**Comment by K1ngfish3r** [comment]
https://github.com/K1ngfish3r/lnreader/actions/runs/6842568235
1. Sign in github
2. Download and Install Artifact
3. More -> Settings -> Advanced -> Clear Database
