### ISSUE TITLE
RoyalRoad: "Finished" chapter name does not show chapter name if there are formatted text in the chapter. Shows the formatted text instead

### ISSUE THREAD

**Issue by anishmworld** [LNReader/lnreader-plugins#644]
### Steps to reproduce

Open any novel chapter that has some formatted text (usually bold).

### Expected behavior

The finished text should always show the chapter name as "Finished: \<chapter name\>" 

### Actual behavior

At the end of the chapter, the "Finished: <chapter name>" text instead shows all the formatted texts in the chapter itself. All the text that was shown instead of the title had formatting like [Death's Duality] in the screenshot below.  
Example chapter from screenshot: https://www.royalroad.com/fiction/24709/defiance-of-the-fall/chapter/1404482/chapter-1099-one-man-calamity 

![Screenshot_2023-11-12-02-58-55-21_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/28841812/d475f81a-40ba-48cf-937f-ec685d8937f6)

### LNReader version

1.1.18

### Android version

Android 12.1

### Device

OnePlus Nord 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
You can try this dev build? https://github.com/K1ngfish3r/lnreader/actions/runs/6842456679
1. Sign in github
2. Download and Install Artifact

Let us know if it is still broken

**Comment by anishmworld** [comment]
Issue seems to be resolved. Screenshot from the same chapter is attached.
Note that I had to delete the downloaded chapter and download again to see
the fix. The error might be in the saves.

**Comment by K1ngfish3r** [comment]
No screenshot found to be attached but since it's fixed that's good.
Since I am only changing the source's fetching logic, chapters already downloaded wont be affected. So yes, having to re-download the chapters is normal.
