### ISSUE TITLE
maigo ni natteita youjo wo tasuketara, otonari ni sumu bishoujo ryuugakusei ga ie ni asobi ni kuru you ni natta ken nitsuite

### ISSUE THREAD

**Issue by Hiro-the-absolute** [LNReader/lnreader-plugins#661]
### Source information

SakuraNovel 

### Steps to reproduce

My issues 
1.When i want to read it, i clicked on my collection. still normal, nothing feels wrong
2.i clicked some chapter and as usual, it would be loading, seems normal
3. The issues when, the loading done, it won't load anything, and when i was trying to download the chapter, it's stuck in the loading

### Expected behavior

i expected if this would load but it'll take a while, cuz my internet is sometimes so slow.

### Actual behavior

But this happened, Kinda disappointed when i was wanted to read it, because the reality, this not caused by my internet, and it shows some code that told me if it can't load the extension

### LNReader version

1.1.15

### Android version

Android 12 

### Other details

The chapter won't downloading, it's stuck in the loading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Fixed in https://github.com/LNReader/lnreader/pull/807
You can get a dev build here https://github.com/LNReader/lnreader/actions/runs/7412799346
1. Sign in Github and download Apk
2. More > Settings > Advanced > Clear Database
3. Try the source, if issue persists, post screenshot here
