### ISSUE TITLE
Release that Witch

### ISSUE THREAD

**Issue by installkode** [LNReader/lnreader-plugins#664]
### Source information

SakuraNovel

### Steps to reproduce

Empty chapters have no content

### Expected behavior

Contents of the chapter

### Actual behavior

Empty chapter

### LNReader version

1.1.18

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Fixed in https://github.com/LNReader/lnreader/pull/807
You can get a dev build here https://github.com/LNReader/lnreader/actions/runs/7412799346
1. Sign in Github and download Apk
2. More > Settings > Advanced > Clear Database
3. Try the source, if issue persists, post screenshot here

**Comment by nyagami** [comment]
duplicated of https://github.com/LNReader/lnreader-plugins/issues/657
