### ISSUE TITLE
Duplicate chapters 

### ISSUE THREAD

**Issue by YokkaF** [LNReader/lnreader-plugins#666]
### Source information

Ranobelib

### Steps to reproduce

1. Discover the novel

### Expected behavior

Chapters in 1 copy

### Actual behavior

Duplicate chapters 

### LNReader version

1.1.18

### Android version

Android 13

### Other details

A problem has been noticed on the novel "shadow slave" ("Теневой раб") 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
It looks fine in v2
You should use v2 beta app or wait for its stable release
