### ISSUE TITLE
Please Add Story Seedlings (previously Travis Translations) 

### ISSUE THREAD

**Issue by Sakya22** [LNReader/lnreader-plugins#667]
### Source name

Story Seedling

### Source link

https://storyseedling.com/

### Language

English

### Other details

Also remove Travis Translations as that website is abandoned in favor of this new website. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Added in https://github.com/LNReader/lnreader-plugins/pull/798
