### ISSUE TITLE
Blank chapters from NovelUpdates source for specific book.

### ISSUE THREAD

**Issue by alexmcgilvery** [LNReader/lnreader-plugins#697]
### Source information

Novel Updates

### Steps to reproduce

Add "I Became a Third-Rate Villain in the Hero Academy" to Library.
Try reading any chapter past the first C1-C4 chapters (ie after translator changed).

### Expected behavior

Chapter not blank.

### Actual behavior

Get Blank Content, no text at all except for "Finished: c5" etc.

### LNReader version

1.1.18

### Android version

Android 11

### Other details

Looks like the same same issue with other novels by https://raeitranslations.com/ on novel updates:
including "Academy's Second Seat", "I Became a 6★ Gacha Character".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
Fixed in 2.0.0 beta.
