### ISSUE TITLE
Sakuranovel

### ISSUE THREAD

**Issue by lorzd** [LNReader/lnreader-plugins#708]
### Source information

Sakuranonel

### Steps to reproduce

Can't read the novel

### Expected behavior

It should read

### Actual behavior

It has cover but can't display the text

### LNReader version

1.1.18

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
duplicated of https://github.com/LNReader/lnreader-plugins/issues/657
