### ISSUE TITLE
"Bulk" request of brazilian sources

### ISSUE THREAD

**Issue by MrChuw** [LNReader/lnreader-plugins#71]
### Source name

Reaper, Saikai, Neox, Arthur, Silence

### Source link

https://reaperscans.com.br / https://saikaiscan.com.br / https://neoxscans.net / https://arthurscan.xyz / https://silencescan.com.br

### Language

Portuguese, Brazilian

### Other details

Some fonts I remember.

**Comment by Mr24257** [comment]
I don't know how to download LN reader  please help me
