### ISSUE TITLE
Readwn occasionally bug

### ISSUE THREAD

**Issue by B3H3M0T** [LNReader/lnreader-plugins#732]
### Source information

https://www.wuxiap.com//novel/people-are-sailing-i-crocodile-will-reach-my-peak-when-i-am-released-from-prison.html

### Steps to reproduce

It only appear on certain title all chapter gone missing, but when open the main web it appear and there no trouble. And it happen because batch download detected by cloudflare and got banned.

### Expected behavior

![Screenshot_2024-01-27-12-07-29-327_com opera browser](https://github.com/LNReader/lnreader-sources/assets/8720422/2471983c-46b5-424d-903e-56caced92be9)

### Actual behavior

![Screenshot_2024-01-27-12-06-45-184_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/8720422/acc6ea04-ff16-47d4-a4fb-b652d9cfd38b)

### LNReader version

1.1.18

### Android version

Android 13

### Other details

All this happened because readwn occasionally change webhost name, making detection gone haywired bug appear occasionally. And because detected by cloudflare and your ip got banned.

https://www.wuxiap.com//novel/people-are-sailing-i-crocodile-will-reach-my-peak-when-i-am-released-from-prison.html

https://www.wuxiap.com//novel/soccer-opening-check-in-with-a-tiger-style-shot.html

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
the site was moved to wuxiav.com
