### ISSUE TITLE
Linovelib - Traditional Chinese support

### ISSUE THREAD

**Issue by alistair3149** [LNReader/lnreader-plugins#744]
### Describe your suggested feature

Would it be possible to add support for Traditional Chinese for Linovelib? Sometimes Chinese sites offer a toggle switch for both Simplified and Traditional Chinese, it might be useful to support language variants like that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by he0119** [comment]
FYI https://github.com/LNReader/lnreader/issues/941

>Should we support multiple lang?
Provide each plugin a storage and let it cook
