### ISSUE TITLE
Traducciones Amistosas (spanish)

### ISSUE THREAD

**Issue by lalalasupa0** [LNReader/lnreader-plugins#753]
### Source name

Nartag (Novels)

### Source link

https://novelas.nartag.com (dead ig)
https://visortraduccionesamistosas.com

### Language

Spanish

### Other details

They are also called "Traducciones Amistosas", but it is, I guess, an old name.

The link https://visortraduccionesamistosas.com is their general one, the other one I put was supposedly their link for novels only, but both work for novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
I rlly want this gets added soon, it's such a great source... Have some GOOD WNs that aren't anywhere else in spanish

**Comment by error7404** [comment]
The site doesn't seem to work for me (infinit loading) are you sure they didn't change URL or something?

**Comment by lalalasupa0** [comment]
> The site doesn't seem to work for me (infinit loading) are you sure they didn't change URL or something?

My bad for not answering... Yeah, it seems et doesn't load...
Instead the url https://visortraduccionesamistosas.com can be used, which is the one they use for everything the do and have (manhwas too)
