### ISSUE TITLE
unexpected storage error

### ISSUE THREAD

**Issue by Huta0c6** [LNReader/lnreader-plugins#755]
### Source information

HakoLightNovel

### Steps to reproduce

1. Download any chapter
2. An error message appears

### Expected behavior

This should download successfully.

### Actual behavior

After displaying the error message, the application still downloads but the chapter has no illustrations (turn off the network and check)

### LNReader version

1.1.19

### Android version

Android 10

### Other details

![Screenshot_2024-02-07-07-46-57-88](https://github.com/LNReader/lnreader-sources/assets/126092312/a2cf4ddc-f6cf-45fb-a814-b89630be4cc7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
It looks like the app has no permission to the Download folder.
Try to clear download folder.
Or you can try v2.0.0
