### ISSUE TITLE
Rewayat Club

### ISSUE THREAD

**Issue by esraahassan2151** [LNReader/lnreader-plugins#78]
### Source name

Rewayat Club

### Source link

https://rewayat.club/

### Language

Arabic

**Comment by deku99hh** [comment]
Why is the source not uploaded?

**Comment by Khalilr28** [comment]
There is a source in the Arabic language that is not present in the program, and it is very well known. I hope you add it, as it is the only thing missing in the program for me. The name of the site is.
rewayat.club.
