### ISSUE TITLE
Chapters from RoyalRoad have "this chapter is stolen" type of text 

### ISSUE THREAD

**Issue by anishmworld** [LNReader/lnreader-plugins#794]
### Source information

RoyalRoad

### Steps to reproduce

Chapters recently pulled from RoyalRoad have "this chapter is stolen" type of text  
See below screenshots from the app and from the site.  Reference chapter: https://www.royalroad.com/fiction/26294/he-who-fights-with-monsters/chapter/1524805/chapter-846-a-cocktail-of-ignorance-arrogance 
App:  

![Screenshot_2024-02-22-09-28-47-70_3c1c179116822eec69c21805387f0489~2](https://github.com/LNReader/lnreader-sources/assets/28841812/f97da160-9a9f-4e22-aecb-c6f811d4d3b3)  
Site:  

![Screenshot_2024-02-22-09-29-11-02_c0dc27f5c07cb0fb3541d6073dfd6932~2](https://github.com/LNReader/lnreader-sources/assets/28841812/4a85a81e-77f4-4116-a275-a12fc76a318b)

### Expected behavior

The highlighted text shouldn't appear 

### Actual behavior

Extra text appears that is not available on the site. 

### LNReader version

1.1.19

### Android version

Android 12.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
seems like be fixed in v2 beta
You can try v2 beta or wait for its stable release
