### ISSUE TITLE
NovelUpdate is not working

### ISSUE THREAD

**Issue by dd5gl** [LNReader/lnreader-plugins#821]
### Source information

NovelUpdates

### Steps to reproduce

Enter the sources in the app
Choose any novel 
The chapters do not appear 
![Screenshot_20240304-165032](https://github.com/LNReader/lnreader-sources/assets/161182079/a485357b-ebe1-4ffc-80b9-7c0e308201f6)

### Expected behavior

Chapters are supposed to appear

### Actual behavior

No chapters appear for any novel

### LNReader version

1.1.19

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by brownnath2000** [comment]
Verify the following: open any book (sourced from Novel Updates) in your Library. Tap WebView, and it should take you to the overview + contents table. Sign into Novel Updates with your account. Close WebView returning to the LNReader. You should open the story back up and refresh by swiping down (similar to refresh on windows).

**Comment by rajarsheechatterjee** [comment]
_A detailed update on Novel Updates has been published [here](https://discord.com/channels/835746409357246465/1202849673153355786)._ 

Closing this as there isn't much the app could do in this situation.
