### ISSUE TITLE
Penguasa Misteri/Lord of the mysteries (Chapter is empty)

### ISSUE THREAD

**Issue by RrvyeeE** [LNReader/lnreader-plugins#827]
### Source information

IndoWebNovel 

### Steps to reproduce

![Screenshot_2024-03-13-23-20-49-49_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/163301492/339eafcc-6699-4f09-8dc3-247fd0af038f)
![Screenshot_2024-03-13-23-37-05-31_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/163301492/0b02ed10-107d-42e9-bc7a-5641634215a2)

### Expected behavior

![Screenshot_2024-03-13-23-23-38-78_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/163301492/b231d32f-6660-4a38-9d46-d3e2c91a26f7)

![Screenshot_2024-03-13-23-37-05-31_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/163301492/b4b57f82-d0ce-4ee4-bf26-8cc2d5d902e3)

### Actual behavior

![Screenshot_2024-03-13-23-20-49-49_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/163301492/8c640da4-8b32-4c18-bfa5-0f69f21d253d)

### LNReader version

1.1.1.9

### Android version

Android 13 

### Other details

chapter is empty, but in WebView it's fine at all 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AhmadNaruto** [comment]
has been fixed

**Comment by nyagami** [comment]
Done in https://github.com/LNReader/lnreader-plugins/pull/882 (beta app)
