### ISSUE TITLE
Update Readwn.com & Novelmt.com

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader-plugins#830]
### Source information

Readwn.com & Novelmt.com

### Steps to reproduce

1. Go to Readwn.com or Novelmt.com.
2. Search any novel on the search bar

### Expected behavior

This should show the searched novel if available.

### Actual behavior

It is doing nothing but displaying the home page of the website 

### LNReader version

1.1.12

### Android version

Android 11 

### Other details

Readwn.com & Novelmt.com has changed their domain name and Also their is no difference between Home Page and Latest Page in the Source. On the website of Readwn.com & Novelmt.com there are the tabs Popular, New, & Updates so Use Popular Tab as Home Page for the source and use Updates for Latest Page or you can add These three Tabs in Filters 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
Readwn.com & Novelmt.com are now redirecting to [Wuxia Fox](https://www.wuxiafox.com) and Wuxia Fox already has a source in beta
[LNReader/lnreader/releases/v2.0.0-beta.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.0)
make sure to convert your backup

**Comment by Pheonix-Flames** [comment]
Done
