### ISSUE TITLE
syosetsu source just shows up no results found screen.

### ISSUE THREAD

**Issue by afat123** [LNReader/lnreader-plugins#835]
### Source information

syosetsu (ID: 36)

### Steps to reproduce

1 = Click syosetsu source
2 = "no result found"

### Expected behavior

Click syosetsu source, shows the novel name in jp. 

### Actual behavior

https://github.com/LNReader/lnreader-sources/assets/65108757/21dfeed3-7acc-40c4-9e5f-2d497114a032

### LNReader version

1.1.19

### Android version

Xiaomi HyperOS 1.0.1.0 / android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
it's fixed in beta
[LNReader/lnreader/releases/v2.0.0-beta.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.0)
make sure to convert your backup

**Comment by nyagami** [comment]
You should use v2 beta app or wait for its stable release
