### ISSUE TITLE
AzoraGo : Add source

### ISSUE THREAD

**Issue by OtakuArab** [LNReader/lnreader-plugins#840]
### Source name

AzoraGo

### Source link

https://azorago.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
the search bar doesn't seem to work, it would be weird to implement it if the search doesn't show any results

(madara)

**Comment by OtakuArab** [comment]
> the search bar doesn't seem to work, it would be weird to implement it if the search doesn't show any results
> 
> (madara)

No, it searches. I tried it with another application and it searches
![Screenshot_٢٠٢٤٠٣١٩-٠١٣٠٢٤](https://github.com/LNReader/lnreader-sources/assets/161339329/7c291bfb-8b9f-4e0e-a198-8ecb52d03aae)
![Screenshot_٢٠٢٤٠٣١٩-٠١٣٢٣٤](https://github.com/LNReader/lnreader-sources/assets/161339329/d4780c39-7c1c-4432-97d6-ee6a1a63fccd)
