### ISSUE TITLE
Futago Matomete “Kanojo” ni Shinai?

### ISSUE THREAD

**Issue by MAMQH** [LNReader/lnreader-plugins#844]
### Source information

Light novel

### Steps to reproduce

Ngga bisa di baca

### Expected behavior

supaya bisa di baca

### Actual behavior

..

### LNReader version

1.1.15

### Android version

10

### Other details

..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing this since the issue template has been filled out properly. Either edit it and add the necessary details or create a new issue.
