### ISSUE TITLE
Kurasu de nibanme

### ISSUE THREAD

**Issue by Kiyotaka101** [LNReader/lnreader-plugins#847]
### Source information

Sakuranovel

### Steps to reproduce

The novel is not open
![Screenshot_20240321_011052](https://github.com/LNReader/lnreader-sources/assets/164225567/dfad4039-46a5-4ec4-9b1e-62fda1bc8c56)

### Expected behavior

The novel is open

### Actual behavior

The novel in not opened

### LNReader version

1.1.19

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
duplicated of https://github.com/LNReader/lnreader-plugins/issues/657
