### ISSUE TITLE
Add source Helscans

### ISSUE THREAD

**Issue by Xeroxiin** [LNReader/lnreader-plugins#877]
### Source name

Helscans

### Source link

https://helscans.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [x] I will fill out all of the requested information in this form.

**Comment by Batorian** [comment]
You can read all novels from Hel Scans via Novel Updates.
