### ISSUE TITLE
Novel hall search doesn't work

### ISSUE THREAD

**Issue by 7Melon7** [LNReader/lnreader-plugins#879]
### Source information

Novel hall

### Steps to reproduce

Open novel hall
Search anything
Reloads the same page when you opened it first
Open WebView
Search work
Exit WebView 
Search still loading same page

### Expected behavior

Show what I was searching for

### Actual behavior

Just reloading same page when you open novel hall first

### LNReader version

2.0.0

### Android version

1.0.8.0 unlimixm

### Other details

In app it's called novel hall previously was called novelhall. I tired scrolling down but there was a dead end after like 50 novels and couldn't scroll anymore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Does the site offer a novel search feature? It seems their search bar is currently returning chapters instead of novels.

**Comment by 7Melon7** [comment]
> Does the site offer a novel search feature? It seems their search bar is currently returning chapters instead of novels.

Yes in WebView or any browser the search works fine and shows novels. Only while using it on the LNReader app it just reloads the latest chapters while searching for anything
