### ISSUE TITLE
 Novels not being updated properly unless removed and re-added in LightNovelPub

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [LNReader/lnreader-plugins#883]
### Source information

LightNovelPub

### Steps to reproduce

1. Pull Down for Update

### Expected behavior

There should be updates for lightnovelpub novels as can be comfirmed by webview

### Actual behavior

No Updates for lightnovelpub novels

### LNReader version

2.0.0-beta.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
done in https://github.com/LNReader/lnreader/pull/1048
just wait for next release of beta
