### ISSUE TITLE
Novel Updates - Chapter Duplication

### ISSUE THREAD

**Issue by unlockthecode** [LNReader/lnreader-plugins#887]
### Source information

Novel Updates

### Steps to reproduce

1. Refresh any novel for updates 
2. It will duplicate (or as I've read in another post, pull chapters from the wrong novels) once a few weeks.
3. The added chapters are permanently there unless maybe I clear the app's storage and files, and then re-add the novels, but then again it will occur.

### Expected behavior

It shouldn't pull chapters that aren't matching the title of the novel nor duplicate its contents.

### Actual behavior

Chapters are duplicated or pulled from other novels and is permanently there.

### LNReader version

1.1.19

### Android version

Android 12

### Other details

This has been resolved back in January I believe, but it has been closed by the bot. Yet here it is occuring once again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
_A detailed update on Novel Updates has been published [here](https://discord.com/channels/835746409357246465/1202849673153355786)._ 

Closing this as there isn't much the app could do in this situation.
