### ISSUE TITLE
O-R-V

### ISSUE THREAD

**Issue by aboutzri** [LNReader/lnreader-plugins#892]
### Source information

IndoWebNovel

### Steps to reproduce

can't open the chapter 

### Expected behavior

.

### Actual behavior

.

### LNReader version

1.1.19

### Android version

Android 12

### Other details

i can't open the chapter 
![Screenshot_20240417_204826](https://github.com/LNReader/lnreader-plugins/assets/167325362/fc444d9e-679e-4432-9c7c-8b320373a0f2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AhmadNaruto** [comment]
fixed

**Comment by nyagami** [comment]
Done in https://github.com/LNReader/lnreader-plugins/pull/882
