### ISSUE TITLE
A Tamer's Path (A Deckbuilding System Apocalypse)

### ISSUE THREAD

**Issue by Armodeco** [LNReader/lnreader-plugins#894]
### Source information

Royal Road

### Steps to reproduce

Open novel, read chapters after chapter 23 onwards.

### Expected behavior

Open chapter, continue with the story

### Actual behavior

Open chapter, error appears with "Chapter is empty. Report on github if it's available in webview."

### LNReader version

1.1.19

### Android version

Android 13

### Other details

The problem starts after seeing repeat chapters. I have opened the using webview and it worked fine. No capcha's were requested or access to cloudfare(based on other similarly reported bugs).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment]
Please try updating the app before creating an issue

**Comment by Armodeco** [comment]
Updated, same problem

**Comment by Armodeco** [comment]
> Please try updating the app before creating an issue

Updated, same issue. Sorry

**Comment by CD-Z** [comment]
Then you can update to the 2.0 beta version, but you will lose your current data in the process. You can use the backup feature however this only saves the novel and not the progress. I tested it already and your novel works fine there.
https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.1

**Comment by nyagami** [comment]
Work fine for me too, try to remove novel > clear cached novels > add it back

**Comment by Armodeco** [comment]
I tried downloading 2.0.0 beta, and it worked. Well with complications in importing my backup from today. I now have to find the novel one by one.

Maybe the second solution could have solved my problem also. But what done is done
