### ISSUE TITLE
Search function is not working in some Novel Sources 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader-plugins#895]
### Source information

Wuxiacity, WuxiaMTL, FanNovel, and Wuxiap 

### Steps to reproduce

1. Add plugins such as Wuxiacity, WuxiaMTL, FanNovel, and Wuxiap to your platform.
2. Open any of the mentioned plugins.
3. Use the search box at the top to search for something specific within the plugin.

### Expected behavior

The search function should display the search results based on the entered text in the search box within the plugin.

### Actual behavior

It doesn't do anything different and doesn't show any changes; it simply displays what is already shown on the homepage

### LNReader version

2.0.0

### Android version

Android 11 

### Other details

1.1.19 also facing Same problem with Readwn and Novelmt

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Wuxiacity and Wuxiap are still working.
