### ISSUE TITLE
Scribble hub broken for 1 series

### ISSUE THREAD

**Issue by nbwang** [LNReader/lnreader-plugins#928]
### Source information

Scribble Hub

### Steps to reproduce

1. Search I Got Summoned And Got Cheat Skills Along With A Yuri Slave Harem in Scribble Hub
2. Add to library
3. Open in WebView

### Expected behavior

This series should be added to library without broken cover and no description and WebView should link to series page and not  page not found

### Actual behavior

When the series is added to library, the cover and description are missing, the WebView links so a 404 not found page

### LNReader version

1.1.19

### Android version

Android 14

### Other details

The link used by the app is different from the website link and for some reason this one series doesn't work with the app link

Website
https://www.scribblehub.com/series/920294/i-got-summoned-and-got-cheat-skills-along-with-a-yuri-slave-harem/

App
https://www.scribblehub.com/read/920294-i-got-summoned-and-got-cheat-skills-along-with-a-yuri-slave-harem/

it's read instead of series after the .com and a - instead of / after the numbers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nbwang** [comment]
Github messed up my fake arrows but it's read instead of series after the .com and a - instead of / after the numbers

**Comment by Batorian** [comment]
Your issue seems to be fixed in the [2.0.0 beta release](https://discord.com/channels/835746409357246465/835873876520730695/1223066973437694042). Should you want to update to 2.0.0, pls do follow the instructions.

**Comment by nyagami** [comment]
v1.1.19 is no longer maintained. Please migrate app to v2 to get quick fixes
