### ISSUE TITLE
re:library

### ISSUE THREAD

**Issue by yuukiw** [LNReader/lnreader-plugins#933]
### Source name

Re:library

### Source link

https://re-library.com

### Language

English

### Other details

Biggest translator of Gender Bender works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
done in https://github.com/LNReader/lnreader-plugins/pull/936
