### ISSUE TITLE
Ranobelib doesnt work

### ISSUE THREAD

**Issue by root-omp** [LNReader/lnreader-plugins#938]
### Source information

Ranobelib(OLD)

### Steps to reproduce

Browse -> RanobeLib
or opening any LN, which was liked from RanobeLib source

### Expected behavior

Source should work as intended

### Actual behavior

Doesn't work at all

### LNReader version

2.0.0

### Android version

Android 13

### Other details

It seems that old.ranobelib.me has a cloudflare protection, so it cant be parsed, but normal ranobelib.me doesnt(as i know)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by VectorNEON** [comment]
old.ranobelib.me I already think it’s time to move to the main new domain, just ranobelib.me

the old one, as was said, has protection from Cloudflare, unlike the usual ranobelib.me (new)
