### ISSUE TITLE
hizoManga don't work

### ISSUE THREAD

**Issue by dd5gl** [LNReader/lnreader-plugins#944]
### Source information

HizoManga

### Steps to reproduce

1- open the source or search for a novel in it.
2- don't work, and T
this is what appears 
![Screenshot_20240521-084218](https://github.com/LNReader/lnreader-plugins/assets/161182079/f6de57eb-d06b-43d3-827c-3b4445bb0fe8)

### Expected behavior

open the source 
All novels appear and work properly

### Actual behavior

Nothing appears even if I open the source WebView or something 

### LNReader version

2.0.0

### Android version

android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
They changed there url from https://hizo manga.me to https://hizomanga.net it's fixed in #920 but I'm not sure when it will get merged
