### ISSUE TITLE
Adding traditional Chinese from linovelib

### ISSUE THREAD

**Issue by waijaii** [LNReader/lnreader-plugins#954]
### Describe your suggested feature

I think adding traditional Chinese version of linovelib would be better for traditional Chinese reader. Currently only simplified Chinese is supported with (https://www.bilinovel.com/).

### Other details

Traditional Chinese is also supported in the same website (https://tw.linovelib.com/) , by the ‘繁體’ button at the lowest in the https://www.bilinovel.com/.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MareDevi** [comment]
this website seems not to support traditional chinese anymore?

**Comment by waijaii** [comment]
> this website seems not to support traditional chinese anymore?

No, it is still supporting

**Comment by MareDevi** [comment]
> > this website seems not to support traditional chinese anymore?
> 
> No, it is still supporting

but when i try to click the '繁體' buttom, the web just refresh and still display simplified chinese, also the `https://tw.linovelib.com/` will redirect to the `www.bilinovel.com`

**Comment by MareDevi** [comment]
> > > > this website seems not to support traditional chinese anymore?
> > > 
> > > 
> > > No, it is still supporting
> > 
> > 
> > but when i try to click the '繁體' buttom, the web just refresh and still display simplified chinese, also the `https://tw.linovelib.com/` will redirect to the `www.bilinovel.com`
> 
> That's weird. I can use the https://tw.linovelib.com normally and not getting redirected back.

oh I found the key
the website would check user's ip address
it will display traditional chinese when i use proxy of hk or tw

**Comment by MareDevi** [comment]
cloud you add `https://raw.githubusercontent.com/MareDevi/lnreader-plugins/plugins/v3.0.0/.dist/plugins.min.json` to your lnreader repo to help me to check if linovelib-tw plugin works well.
due to the network problem i cloudn't test thorough it

**Comment by waijaii** [comment]
Hi, it works perfectly fine, photos are loaded and the novel works well. Thanks!

> could you add `https://raw.githubusercontent.com/MareDevi/lnreader-plugins/plugins/v3.0.0/.dist/plugins.min.json` to your lnreader repo to help me to check if linovelib-tw plugin works well. due to the network problem i cloudn't test thorough it
