### ISSUE TITLE
Sub-Titles are incorrectly displayed

### ISSUE THREAD

**Issue by root-omp** [LNReader/lnreader-plugins#960]
### Source information

Ranobelib

### Steps to reproduce

![Screenshot_2024-05-28-16-33-40-91_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-plugins/assets/58180434/d9f58f6a-660e-45c8-9fdf-90099eac7f9f)
screen from random chapter from classroom of elite

### Expected behavior

for example in rulate:
![Screenshot_2024-05-28-16-39-38-24_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-plugins/assets/58180434/85cc105d-4a25-4bf7-8f15-3aafa577937d)

### Actual behavior

incorrectly displayed

### LNReader version

2.0.0(i have used last file from build actions)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rider21** [comment]
Can you provide the `heading` / `link` of the chapter?
I can't find a chapter that has a `heading` tag.

**Comment by root-omp** [comment]
> Can you provide the `title` / `link` of the chapter?
> I can't find a chapter that has a `heading` tag.

Том 28 Глава 1 Скрытое в личном собеседовании
https://ranobelib.me/ru/6709--youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-novel/read/v28/c1
