### ISSUE TITLE
Installation failed: RanobeLib

### ISSUE THREAD

**Issue by ViruzSS** [LNReader/lnreader-plugins#962]
### Source information

RanobeLib

### Steps to reproduce

1. Browse
2. Available
3. "Русский"
4. Try install "RanobeLib" 

### Expected behavior

RanobeLib should be installed

### Actual behavior

Give an error message

### LNReader version

2.0.0

### Android version

Android 11

### Other details

![Screenshot_2024-05-29-08-41-12-487_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-plugins/assets/168935089/f1a796d7-8dd2-4e70-a65c-be0a5401a761)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Ranobelib is not ready for current beta. You should use this [dev build](https://github.com/LNReader/lnreader/actions/runs/9266345221).
Remember to backup your data with Google Drive
