### ISSUE TITLE
Chapter is empty - Error 404

### ISSUE THREAD

**Issue by ViruzSS** [LNReader/lnreader-plugins#963]
### Source information

RanobeLib

### Steps to reproduce

1. Open RanobeLib (Already in Dev Build)
2. Open ranobe "Точка зрения всеведущего читателя"
3. Open any chapter

### Expected behavior

This should direct to the chapter on website

### Actual behavior

Instead, it directs to another link that leads to a 404

### LNReader version

2.0.0 (dev build) 

### Android version

Android 11

### Other details

Surprisingly, this only happens with this ranobe, which is very depressing
![Screenshot_2024-05-30-00-12-07-503_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-plugins/assets/168935089/4aeb3a22-9267-482f-a135-75ebc83c97f4)
![Screenshot_2024-05-30-00-12-27-073_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-plugins/assets/168935089/2667bc89-ccc8-42e9-9a39-a31aeb86ac93)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
It works for me.
Try to open plugin in webview

![Uploading Screenshot_20240530-091613.png…]()

**Comment by Rider21** [comment]
Some books can only be read with authorisation
Try authorising via the web view and then restart the app.

**Comment by ViruzSS** [comment]
I've cleared cookies and chapters cache, then everything became good, ty everyone for your help
