### ISSUE TITLE
Infinte loading screen

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#964]
### Source information

فضاء الروايات (riwayat)

### Steps to reproduce

Click on any novel in the mentioned source. Infinite loading screen with no sign of change 

### Expected behavior

The novel to appear normally with the chapters list

### Actual behavior

Infinite loading screen

### LNReader version

2.0.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mingo3347** [comment]
I really appreciate the quick solving of the loading problem in the riwayat source. But now there's this link when you click on the chapter ( inside the chapter itself) on any novel and a white mini loading screen that appears and then disappears, but appears again each time you change between previous or following chapters. Sent from my Galaxy
-------- Original message --------From: nyagami ***@***.***> Date: 5/30/24  7:42 PM  (GMT+02:00) To: LNReader/lnreader-plugins ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [LNReader/lnreader-plugins] Infinte loading screen (Issue #964) 
Closed #964 as completed via #965.

**Comment by error7404** [comment]
Can you open a new issue on GitHub with a video and detail about the novel name and chapter number please?
