### ISSUE TITLE
Adicionar uma nova fonte para ler light novel

### ISSUE THREAD

**Issue by Ewe5002** [LNReader/lnreader-plugins#981]
### Source name

Tsundoku Traduções 

### Source link

https://tsundoku.com.br/

### Language

Português 

### Other details

![Screenshot_20240608_210740_Chrome](https://github.com/LNReader/lnreader-plugins/assets/172156349/50ef93a7-4c9a-4212-a53e-885484afcdaa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
done in #1067
