### ISSUE TITLE
The site domain changed

### ISSUE THREAD

**Issue by x7sony** [LNReader/lnreader-plugins#985]
### Source information

KolNovel in arabic section

### Steps to reproduce

Click on the sourse

### Expected behavior

The novels should appear

### Actual behavior

It tell there are no results found

### LNReader version

1.1.19

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
You can try the beta it works fine there, but you will lose your current data in the process. You can use the backup convertion feature however this only saves the novel and not the progress.
https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.1

**Comment by rajarsheechatterjee** [comment]
Resolved in commit 4bd7df1d61c84b26e3ce3b847b432b13430c0570
